import os
import re

def parse_frontmatter(filepath):
    title = os.path.basename(filepath)
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            if lines and lines[0].strip() == '---':
                for line in lines[1:]:
                    if line.strip() == '---':
                        break
                    if line.startswith('title:'):
                        title = line.replace('title:', '').strip()
                        # Remove quotes if present
                        title = title.strip('\'"')
    except Exception:
        pass
    return title

def generate_index(docs_dir):
    categories = {
        "concepts": "Concepts",
        "adr": "Architecture Decision Records",
        "arch": "Architecture Blueprints",
        "patterns": "Patterns & Idioms",
        "guides": "Guides & Best Practices",
        "learn": "Learnings & Sessions"
    }

    generated_content = "<!-- AUTOGENERATED INDEX START -->\n\n## 📋 Vollständiger Index\n\n"

    for cat_dir, cat_name in categories.items():
        cat_path = os.path.join(docs_dir, cat_dir)
        if not os.path.exists(cat_path):
            continue
            
        generated_content += f"### {cat_name}\n\n"
        
        files = [f for f in os.listdir(cat_path) if f.endswith('.md')]
        files.sort()
        
        if not files:
            generated_content += "*Keine Dokumente in dieser Kategorie.*\n\n"
            continue
            
        for file in files:
            filepath = os.path.join(cat_path, file)
            title = parse_frontmatter(filepath)
            # Create a markdown link relative to INDEX.md
            generated_content += f"- [{title}]({cat_dir}/{file})\n"
            
        generated_content += "\n"
        
    generated_content += "<!-- AUTOGENERATED INDEX END -->"
    
    index_path = os.path.join(docs_dir, "INDEX.md")
    if os.path.exists(index_path):
        with open(index_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Replace existing autogenerated block or append
        pattern = r"<!-- AUTOGENERATED INDEX START -->.*<!-- AUTOGENERATED INDEX END -->"
        if re.search(pattern, content, flags=re.DOTALL):
            new_content = re.sub(pattern, generated_content, content, flags=re.DOTALL)
        else:
            new_content = content + "\n\n" + generated_content
            
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print("Updated INDEX.md")
    else:
        print(f"INDEX.md not found at {index_path}")

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    docs_dir = os.path.join(os.path.dirname(current_dir), "docs")
    generate_index(docs_dir)
